name: Update Price History Daily

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  update-price-history:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r hydration_price_tracker/requirements.txt

    - name: Run update script
      run: |
        python hydration_price_tracker/update_prices.py
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}

    - name: Set Git identity
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit and push if changed
      run: |
        git add price_history.csv
        git commit -m "Auto-update price data" || echo "No changes to commit"
        git push
